// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9iJyz9k-iWd-lmhs0JV0n5s-RQHV3W10',
    appId: '1:749621297064:web:bcea5759907eb1faa3a79d',
    messagingSenderId: '749621297064',
    projectId: 'rkd-app',
    authDomain: 'rkd-app.firebaseapp.com',
    storageBucket: 'rkd-app.firebasestorage.app',
    measurementId: 'G-D9MHPCN434',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXsCPeUNFyc4PA1iiRPIGkNOqQcADaqAo',
    appId: '1:749621297064:android:e1f41f2dec326536a3a79d',
    messagingSenderId: '749621297064',
    projectId: 'rkd-app',
    storageBucket: 'rkd-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASF2jPRSN8pEEUOE9aHpuJG_Wh61EtVVA',
    appId: '1:749621297064:ios:69db5d6ec54d8ad8a3a79d',
    messagingSenderId: '749621297064',
    projectId: 'rkd-app',
    storageBucket: 'rkd-app.firebasestorage.app',
    iosBundleId: 'com.example.businessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASF2jPRSN8pEEUOE9aHpuJG_Wh61EtVVA',
    appId: '1:749621297064:ios:69db5d6ec54d8ad8a3a79d',
    messagingSenderId: '749621297064',
    projectId: 'rkd-app',
    storageBucket: 'rkd-app.firebasestorage.app',
    iosBundleId: 'com.example.businessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9iJyz9k-iWd-lmhs0JV0n5s-RQHV3W10',
    appId: '1:749621297064:web:772da8ae333165e8a3a79d',
    messagingSenderId: '749621297064',
    projectId: 'rkd-app',
    authDomain: 'rkd-app.firebaseapp.com',
    storageBucket: 'rkd-app.firebasestorage.app',
    measurementId: 'G-LHMVLBXM8C',
  );

}