platform :ios, '13.0'

# Absolute path fallback helper for Flutter plugins
flutter_install_from_path = File.join(File.dirname(File.expand_path(__FILE__)), 'Flutter', 'podhelper.rb')
require flutter_install_from_path

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.expand_path(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end